# Generated by Django 3.2.7 on 2021-12-01 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
