# Generated by Django 3.2.7 on 2021-12-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_venta_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='iva',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
