# Generated by Django 3.2.7 on 2021-09-19 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_venta_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='detalles',
        ),
        migrations.AddField(
            model_name='detalles',
            name='subtotal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalles',
            name='venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venta.venta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='iva',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
