# Generated by Django 3.2.7 on 2021-09-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedor'},
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(max_length=150, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.CharField(max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='empresa',
            field=models.CharField(max_length=150, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero',
            field=models.CharField(max_length=150, null=True, verbose_name='Numero Telefonico'),
        ),
    ]
