# Generated by Django 3.2.7 on 2021-09-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20210917_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precioNoIVa',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='pvp',
            field=models.IntegerField(default=1, verbose_name='Precio venta publico'),
            preserve_default=False,
        ),
    ]
