# Generated by Django 3.2.7 on 2021-10-16 22:55

from django.db import migrations
import django.db.models.deletion
import select2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('automovil', '0001_initial'),
        ('categoria', '0001_initial'),
        ('marca', '0001_initial'),
        ('proveedor', '0001_initial'),
        ('producto', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='automovil',
            field=select2.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automovil.automovil'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=select2.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=select2.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marca.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=select2.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
        ),
    ]
