# Generated by Django 3.2.7 on 2021-09-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('modelo', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('pais', models.CharField(max_length=150, verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Automovil',
                'verbose_name_plural': 'Automovils',
            },
        ),
    ]
