# Generated by Django 3.2.7 on 2021-09-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovil',
            name='modelo',
            field=models.CharField(max_length=150, verbose_name='modelo'),
        ),
    ]
